package-lock.json, src/App.js, src/components/Home.js
Select which event you would like to see
=> event list and display basic info

.gitignore, package-lock.json, package.json, src/actions/indexActions.js, src/components/Event.js, src/components/EventSelector.js, src/components/Nav.js, src/components/Router.js, src/components/Router.min.css, src/components/Router.scss, src/constants/Constants.js, src/index.js, src/reducers/rootReducer.js
If you don't know react, this might not make much sense. If you know react, this might not make much sense. 
I was using query param to determine which event to show in the app. With Redux we can store that data in the store instead of checking against the query param.
Now, the param is only used when the app is refreshed or linked to. In that case, we find the query param, and then set up the store based on that param. If no param, display home page.
Sorry for the big PR, I should have split it up so the code is easier to understand.
I (or Jacques) will teach everyone how redux works soon
If you're doing a real CR it'll be helpful to look at it commit by commit
=> Install redux

.firebaserc, .gitignore, firebase.json, package-lock.json, public/index.html
- If you don't know what this is, ask first! These steps are only for those who are handling CI
- Ask a current developer for access to the Firebase project (via Google account)
- `npm install -g firebase-tools` to install necessary packages for CI
- `firebase login:ci` to login to your Google account. SAVE THE TOKEN. I highly recommend declaring it as an environment variable in `.bashrc` or `.zshrc` depending on your system. If you save it as `FIREBASE_TOKEN`, you won't need include the token with every CI command later.
- `firebase init` in your project root directory. Answer the following prompts as so:
- Choose the existing **bt-web** project
- Choose hosting
- *What do you want to use as your public directory? (public)* **build**
- *Configure as a single-page app (rewrite all urls to …
=> Init firebase

.gitignore, package-lock.json, package.json, yarn.lock
Clean up the packages before moving forward
=> Adin house keeping

package-lock.json, package.json, public/index.html, src/components/EventUserTable.js
- installed complementary material-ui library `material-table`
- added CDN link in html head to load material ui icons
- modified using new MaterialTable
- loads in 200 users for testing search
- added search bar at top right
=> Search event table

package-lock.json, package.json, src/components/Authentication/Login.js, src/components/Forms/NewEventForm/NewEventForm.js, src/components/Forms/NewEventForm/NewEventFormComponent.js, src/utils/index.js
New event form will call the backend on submit now
=> Integrate new event form

src/aws-config.js, src/components/Nav.js, src/components/Pages/EventPage.js, src/components/Router.js, src/pages/EventPage.js
- href="/page" displays Event page with URL to all events from Redux
- href="/page?id=something" displays event information (banner, name, description) with registration button
- registration button has NOT been routed to Andy's form but the code to route it to Andy's form is in Router.js (commented out)
=> Event page

package-lock.json, package.json, src/components/Authentication/Login.js
=> Fix login persist by updating aws-amplify

src/actions/PageActions.js
=> Fix home button

src/components/Forms/EditEventForm/EditEventForm.js, src/components/Forms/EditEventForm/EditEventFormComponent.js, src/components/Forms/NewEventForm/NewEventForm.js, src/components/Forms/NewEventForm/NewEventFormComponent.js
`location` is a reserved field name in dynamodb ;/
=> Change location to elocation

src/components/EventForm/EventFormWrapper.js, src/components/Forms/EditEventForm/EditEventForm.js
Fix prod not working because it wasn't using authentication headers
=> Use fetch Util to sign up for event

package-lock.json, package.json, src/actions/UserActions.js, src/components/Authentication/Login.js, src/components/Authentication/LoginRedirect.js, src/components/Messages/RegisterAlert.js, src/components/Messages/index.css, src/components/Router.js, src/pages/member/NewMemberRegister.js
Closes [#68](https://github.com/ubc-biztech/serverless-biztechapp/issues/68)
- Adds `student_id` attribute for users in the user pool
- Removes dependency on `users/get?email=...` so [Derek's refactor](https://github.com/ubc-biztech/serverless-biztechapp/pull/65) should no longer be blocked 
:warning: The PR assumes that we will not be implementing normal email-password signups through Cognito in the near future.
The PR currently works with stage database `biztechUsers` on DynamoDB. Will need to add the custom attribute `student_id` to `biztechUsersPROD` before pushing to production branch.
=> Add custom student_id attribute to amplify

src/components/Forms/EditEvent.js, src/components/Forms/NewEvent.js, src/components/Forms/RegisterEvent.js, src/pages/admin/EventEdit.js, src/pages/admin/EventNew.js, src/pages/member/EventRegister.js
Haven't added the link to the actual event page yet because idk where the designers are going to put it
Closes #97 and #101
=> Event form - add fb url and improve UI

src/actions/UserActions.js, src/components/Authentication/Login.js, src/components/Authentication/LoginRedirect.js, src/components/Forms/NewMember.js, src/components/Nav.js, src/components/Router.js, src/pages/admin/AdminHome.js, src/pages/member/Signup.js, src/utils/index.js
- Fixes bug where missing user in DB keeps calling `users/:id`
- Change `setUser` so that it can hold all user data, not just auth user data
- Add a `timeoutRedirect` so that the login-redirect page doesn't poll infinitely 
- Add a `updateUsers` function to get user info from backend and update redux
=> Fix infinite poll for user

package-lock.json, package.json, src/components/Forms/EditEvent.js, src/components/Forms/NewEvent.js, src/pages/admin/EventEdit.js, src/pages/admin/EventNew.js
- added longitude and latitude fields to new event form and edit event form
- modified the Yup requirements for long/lat as needed 
- added a few buttons for the top 5 most common event locations from a quick glance through UBC BizTech event locations
- added an "info" icon that explains to execs why we want long/lat and how to get those values from Google Maps.
=> added long/lat fields and buttons for common event locations for biztech

package-lock.json, package.json, src/components/EventView.js, src/components/Forms/EditEvent.js, src/components/Forms/NewEvent.js, src/components/Markdown.js, src/pages/admin/EventEdit.js, src/pages/admin/EventNew.js, src/pages/member/EventRegister.js
because i removed the api call in router, some pages need to update the events manually
also fix form error in edit event
closes #125
closes #107
=> Fix event loading / Rich Text Forms

src/pages/member/UserEvents.js
Noticed that the cards don't always resize when screen size changes
- renaming `isNotMobile` --> `isMobile`
- adding `isMobile` as a dependency to re-render the cards
=> Hotfix for cards not responding to width changes

package-lock.json, src/components/EventUserTable.js, src/pages/member/QuickRegister.js, src/pages/member/UserEvents.js
=> redirected event click to eventDetails and minor lint fixes

src/pages/member/UserHome.js
=> adjusted user home container to adjust based on screen size

src/onboarding.txt
created onboarding.txt, everyone please add your name and create a PR
=> added my name

src/onboarding.txt
=> hello hehe

.firebaserc, .github/workflows/deploy-prod.yml, .travis.yml, README.md
- Change travis to deploy to production only using `prod` branch 
- Setup travis to deploy to staging using `master` branch
- change travis to use a token using `dev@ubcbiztech.com` instead of `ianmah@gmail.com`
📷 Screenshots
=> staging deployment (need to test)

src/components/Event/EventCard.js, src/constants/_constants/config.js, src/pages/admin/Event/EventCreate/EventCreateForm.js, src/pages/admin/Event/EventCreate/index.js, src/pages/admin/Event/EventEdit/EventEditForm.js, src/pages/admin/Event/EventEdit/index.js, src/pages/admin/Event/EventStats/EventStatsTable.js, src/pages/admin/Event/EventStats/index.js, src/pages/admin/Home.js, src/pages/admin/index.js, src/pages/member/MemberCreate/index.js, src/pages/public/Event/index.js, src/pages/public/EventsDashboard.js, src/router.js, src/store/event/eventActions.js
👷 Changes: Fixes the endpoints to call the backend requests correctly.
📷 Screenshots
=> Fix endpoints

src/pages/member/Event/QuickRegisterForm.js, src/pages/member/MemberCreate/MemberCreateForm.js, src/pages/public/Event/EventRegister/EventRegisterForm.js, src/pages/public/Event/EventRegister/index.js
👷 Changes: Fixes the registration button.
📷 Screenshots
=> Registration working

src/pages/public/Login.js, src/pages/public/LoginRedirect.js, src/router.js, src/utils/_utils/checkFeatureFlag.js
show /login page, change maxVP toggle parsing, prevent user login (only allow exec login)
📷 Screenshots
=> Exec Only Login

src/constants/_constants/registration.js, src/pages/admin/Event/EventStats/EventStatsTable.js, src/pages/public/Event/EventRegister/EventRegisterForm.js, src/pages/public/Event/EventRegister/index.js
Frontend changes to match the backend refactor to allow for user creation for non ubc students. id = email, studentId = student  number
📷 Screenshots
=> update registration form for non ubc student

.travis.yml, src/pages/public/Event/EventRegister/EventRegisterForm.js, src/pages/public/Event/EventRegister/index.js
Add a select option to opt into trading group or not
backend also needs to be changed in order to take this field
📷 Screenshots
=> trading group option

src/pages/public/Event/EventRegister/index.js
- set authenticatedCall = false for users POST and registration POST (for registration form)
📷 Screenshots
=> changed unauthenticated call for registration form

src/pages/admin/Event/EventStats/EventStatsTable.js, src/pages/admin/Home.js, src/router.js
- remove redundant "BizTech Admins" header
- add margin to statistic
- remove unnecessary state variables
📷 Screenshots
=> minoir tweaks to UI

src/pages/public/Landing.js
=> fix bug with markdown

src/pages/public/Login.js
=> remove sign up text

package-lock.json, package.json, src/context/ThemeContext.js, src/pages/admin/Event/EventCreate/EventCreateForm.js, src/pages/admin/Memberships/Questions/Questions.js
🎟️ Ticket(s): Closes #204 
Changed input field bottom border to white
Fixed calender styling 
📷 Screenshots
=> Event create styling change

src/context/ThemeContext.js
=> Changed clock number color

src/components/inputs/CustomSelect.js, src/pages/public/Event/EventRegister/EventRegisterForm.js, src/pages/public/Event/EventRegister/index.js
- add requirement to check off that they have signed up on lu.ma
- fix border radius for select on mobile view
- add "I'm already a member" option for UBCTG Membership
📷 Screenshots
=> FinTech Event Fixes

src/components/Event/EventView.js
This is a very temporary fix for the dimensions of the image given by design team 
📷 Screenshots
=> change dimension of image

src/pages/public/Event/EventRegister/EventRegisterForm.js, src/pages/public/Event/EventRegister/index.js
=> made trading group question mandatory

src/pages/admin/Memberships/Questions/Questions.js, src/pages/public/Event/EventRegister/EventRegisterForm.js
=> Added 'Other' and 'Not applicable' to Faculty & Level of study dropdowns

src/pages/admin/Event/EventEdit/index.js
- changed route of successful edit from a non existent path to admin/home
- refresh window to reflect the updated change
- in the future, refactor redux so that a window refresh is not needed. Instead we should update the redux store
📷 Screenshots
=> Successful Edit Tweaks

src/components/Event/EventView.js
removed duplication
📷 Screenshots
=> removed duplicated registration header

src/pages/public/Event/EventRegister/EventRegisterForm.js, src/pages/public/MembershipForm/MembershipForm.js, src/pages/public/MembershipForm/index.js
=> Membership Form manual payment to Rita

src/pages/public/MembershipForm/MembershipForm.js, src/pages/public/MembershipForm/MembershipFormSuccess.js, src/pages/public/MembershipForm/index.js
=> Changed topics to text field

src/pages/public/MembershipForm/index.js
Updating the membership form description.
📷 Screenshots
=> Change membership form description so non-ubc students pay 7.50

src/components/inputs/CustomSelect.js, src/components/inputs/CustomTextField.js, src/pages/public/MembershipForm/MembershipForm.js
=> fixed mobile view & white autofill backgrounds & updated styling for consistency

.eslintrc.js, src/components/inputs/CustomTextField.js, src/pages/public/Event/EventRegister/EventRegisterForm.js, src/pages/public/Event/EventRegister/index.js
Hard-coded questions for CareersInTech.
It's already up on PROD at https://app.ubcbiztech.com/event/2021-careers-in-tech/2021/register
It seems like eslint and prettier keep conflicting with each other. I've set eslint to want double-quotes for strings right now, but maybe we want a general fix for this in the future https://www.robinwieruch.de/prettier-eslint
📷 Screenshots
These changes are already on PROD, see the link above
=> CareersInTech Hard-Coded form

src/pages/public/Event/EventRegister/EventRegisterForm.js, src/pages/public/Event/EventRegister/index.js
=> Blueprint hardcoded form

.eslintrc.js, .prettierrc.json, package-lock.json, package.json, src/pages/public/Event/EventRegister/EventRegisterForm.js
Modified configuration for eslint and prettier to avoid conflicts between them, following some of the instructions in this blog post: https://www.robinwieruch.de/prettier-eslint/
Prettier should be configured to handle stylistic checks and formatting, while eslint should catch actual code smells/problems.
📷 Screenshots
=> Resolve conflicts between prettier and eslint

src/components/inputs/CustomSelect.js, src/pages/member/MemberProfile/index.js, src/pages/public/Event/EventDetails/index.js, src/pages/public/Event/EventRegister/index.js, src/pages/public/EventsDashboard.js, src/store/user/userActions.js
=> fix master conflicts

src/pages/public/Landing.js, src/router.js
🎟️ Ticket(s): Closes Home Renovation page fixes
Added a home button on the Home Renovations page which redirects to login/home page of the user (depending on login status). When the user first accesses the web app, it redirects to login/home page of the user (depending on login status).
The code inside Landing.js just redirects user to the root of the file when the Home Button is pressed. Then, router.js takes over, in which the root path is specified to have a login check and hence make the necessary redirects.
📷 Screenshots
=> Added Home Button to "Home Renovations" page

src/pages/public/LoginRedirect.js
=> fix admin login

src/pages/admin/Event/EventStats/EventStatsTable.js
🎟️ Ticket(s):
👷 Changes: QR scanner would automatically re-scan a QR code if it was held on the scanner for too long. This would produce an error message because the QR code was already scanned less than a second ago. This has been fixed, and more robust error-handling has been added while trying to determine other edge-cases
📷 Screenshots
=> QR code scanner polling hotfix

package-lock.json, src/pages/admin/DynamicForm/FormCreate.js, src/pages/admin/DynamicForm/FormRegister.js
=> In dev dynamic question

src/pages/public/RegistrationForms/MembershipForm/MembershipForm.js, src/pages/public/RegistrationForms/UserMembershipForm/UserMembershipForm.js
=> fix missing checkbox imports

src/pages/admin/Memberships/Memberships.js, src/store/memberships/membershipActions.js
=> fix admin members query

src/components/layout/Navigation.js, src/pages/admin/DynamicForm/EventRegisterSuccess.js, src/pages/admin/DynamicForm/FormCreate.js, src/pages/admin/DynamicForm/FormRegister.js, src/pages/admin/Event/EventStats/EventStatsTable.js, src/pages/admin/Event/EventStats/utils.js, src/pages/admin/Memberships/Memberships.js, src/pages/admin/Memberships/Summary/Summary.js, src/pages/public/EventsDashboard.js, src/pages/public/RegistrationForms/FormSuccess.js
=> Qa fixes dev

src/pages/admin/Event/EventStats/EventStatsTable.js
=> fix stat overflow on mobile

src/components/LoginAccess/LoginAccess.js, src/pages/admin/Home.js, src/pages/public/RegistrationForms/MembershipForm/index.js, src/pages/public/RegistrationForms/UserMembershipForm/index.js
=> Styling improvements dev

src/components/LoginAccess/LoginAccess.js, src/pages/admin/Home.js, src/pages/public/RegistrationForms/MembershipForm/index.js, src/pages/public/RegistrationForms/UserMembershipForm/index.js
=> Styling improvements

src/pages/admin/Event/EventStats/EventStatsTable.js
- prevent cancelled and waitlisted users from advancing to check-in
- add another error to differentiate between random QR code vs. BizTech QR code for a different event
📷 Screenshots
=> Improve QR code robustness

src/pages/admin/DynamicForm/FormRegister.js, src/pages/admin/Memberships/Questions/Questions.js, src/pages/admin/Memberships/Summary/Summary.js, src/pages/public/RegistrationForms/MembershipForm/index.js, src/pages/public/RegistrationForms/UserMembershipForm/index.js
=> fix membership pages, registration form login

src/pages/admin/DynamicForm/FormCreatePreview.js, src/pages/admin/DynamicForm/FormRegister.js
🎟️ Ticket(s):
Adds support for newline formatting to description text
📷 Screenshots
=> Fix description formatting on event page view

src/components/LoginAccess/LoginAccess.js, src/pages/admin/DynamicForm/FormCreate.js, src/pages/admin/DynamicForm/FormRegister.js
=> add warning when capacity of event is low

src/pages/admin/DynamicForm/FormCreate.js, src/pages/admin/DynamicForm/FormRegister.js
=> fix lint issues

src/pages/admin/DynamicForm/FormRegister.js
=> remove console log

src/pages/admin/DynamicForm/FormRegister.js
=> allow users to cancel/reregister for events

src/components/Event/EventCard.js, src/pages/admin/DynamicForm/FormRegister.js, src/pages/admin/Home.js
=> Dev to master

src/pages/member/Home/index.js
=> fix eslint

src/pages/public/RegistrationForms/MembershipForm/MembershipForm.js, src/pages/public/RegistrationForms/MembershipForm/index.js, src/pages/public/RegistrationForms/UserMembershipForm/UserMembershipForm.js, src/pages/public/RegistrationForms/UserMembershipForm/index.js
=> add heardFromSpecify field to members

src/pages/admin/DynamicForm/FormCreate.js, src/pages/admin/DynamicForm/FormCreatePreview.js, src/pages/admin/DynamicForm/FormRegister.js, src/pages/admin/DynamicForm/components/CustomQuestion.js, src/pages/admin/DynamicForm/components/QuestionPreview.js
=> add char limit to text questions, image option for all

src/pages/member/Home/index.js
🎟️ Ticket(s): Closes #NA
Adds guard to ensure only published events can be featured.
=> Makes sure only published events are featured

src/pages/admin/Event/EventStats/EventStatsTable.js
=> Hello hacks reg table dev

src/components/Event/EventCard.js, src/pages/admin/DynamicForm/EventRegisterSuccess.js, src/pages/admin/DynamicForm/FormCreate.js, src/pages/admin/DynamicForm/FormRegister.js, src/store/user/userReducer.js
=> Event stripe integration dev

src/pages/admin/Event/EventStats/DraggableTitle.js, src/pages/admin/Event/EventStats/EventStatsTable.js, src/pages/admin/Event/EventStats/utils.js
🎟️ Ticket(s): Closes Registration Table Features story for improved exec usability
- Sort, filter, drag
- Auto-refresh table on QR scans
- Waitlist capability
- Export CSV will now provide data of entire event
- Refer to "Registration Table Feature" overview on Notion for more details
📷 Screenshots
=> Registration Table Enhancements

src/components/Event/EventCard.js, src/pages/admin/DynamicForm/EventRegisterSuccess.js, src/pages/admin/DynamicForm/FormCreate.js, src/pages/admin/DynamicForm/FormRegister.js, src/pages/admin/Event/EventStats/DraggableTitle.js, src/pages/admin/Event/EventStats/EventStatsTable.js, src/pages/admin/Event/EventStats/utils.js, src/store/user/userReducer.js
=> Event stripe tables master

src/pages/admin/DynamicForm/FormCreatePreview.js
=> add diet to form preview

src/pages/admin/DynamicForm/FormCreatePreview.js, src/pages/admin/Event/EventStats/EventStatsTable.js, src/pages/admin/Event/EventStats/utils.js
=> Fix preview popover

package-lock.json, package.json, src/pages/admin/DynamicForm/EventRegisterSuccess.js, src/pages/admin/DynamicForm/FormRegister.js, src/pages/admin/Event/EventStats/EventStatsTable.js
=> Nonmember fixes dev

package-lock.json, package.json, src/pages/admin/DynamicForm/EventRegisterSuccess.js, src/pages/admin/DynamicForm/FormRegister.js, src/pages/admin/Event/EventStats/EventStatsTable.js
=> Nonmember fixes

src/components/alerts/UserAlert.js, src/pages/admin/DynamicForm/EventRegisterSuccess.js, src/pages/admin/DynamicForm/FormCreate.js, src/pages/admin/DynamicForm/FormCreatePreview.js, src/pages/admin/DynamicForm/FormRegisterPartner.js, src/pages/admin/Event/EventStats/EventStatsTable.js, src/pages/admin/Event/EventStats/utils.js, src/pages/public/Event/index.js
=> partner reg form

src/pages/public/EventRedeem/index.js, src/router.js
=> add dynamic qr calls with url params

src/pages/public/EventRedeem/index.js
=> Gamification redeem dev

src/components/alerts/UserAlert.js, src/pages/public/EventRedeem/index.js
=> remove user alert on redemption page

src/pages/public/EventRedeem/index.js
=> remove authentication requirement

src/components/alerts/MemberAlert.js, src/components/layout/Footer.js, src/components/layout/Navigation.js
=> add redeem to ignorepaths

src/pages/public/Gamification/Redemption/index.js
=> Redeem redirect

package-lock.json, package.json, src/pages/public/Companion/biztecho.webflow.css, src/pages/public/Companion/index.js
🎟️ Ticket(s):
Blueprint 2023 Gamification
- Styling for the welcome page
- Minor style edits on the companion
Another package was added, will need to `npm install --legacy-peer-deps` again
📷 Screenshots
=> Gamification styling 1

src/pages/public/Companion/index.js
=> add back text

src/pages/public/Companion/biztecho.webflow.css, src/pages/public/Companion/index.js
Fixed styling of navbar and schedule section.
📷 Screenshots
- [ x] Looks good on large screens
- [ x] Looks good on mobile
=> Companion frontend changes

src/pages/public/Companion/index.js
=> fix contact email

src/pages/public/Companion/GamificationActivityTable.js, src/pages/public/Companion/biztecho.webflow.css
=> reposition animation, add kickoff event

src/pages/public/Companion/ResetPage.js, src/pages/public/Companion/index.js, src/router.js
🎟️ Ticket(s):
Blueprint 2023 Companion
- add in-app QR code used for check-in with a toggle button
- add Companion email reset route
📷 Screenshots
=> Companion Final Quality of Life Changes

src/pages/public/Companion/index.js
=> remove table number

src/pages/admin/Event/EventStats/EventStatsTable.js, src/pages/admin/Event/EventStats/TableColumns.js, src/pages/admin/Event/EventStats/utils.js
🎟️ Ticket(s): Team support for Events on the frontend, InnoVent story 6
- support admin team formation on events admin table
- allow execs to see a user's team ID
- move points column to be near the front
- this is the bare minimum to allow team formation, we don't support swapping on the web app yet. will need to do manually through DB
📷 Screenshots
=> MVP team support on Events

src/components/layout/Navigation.js, src/pages/admin/Companion/index.js, src/pages/admin/index.js
=> companion qr functionality admin side

src/pages/public/Companion/index.js, src/pages/public/Gamification/Redemption/index.js
🎟️ Ticket(s): Closes # n/a
Changed the flag for "negativePointsConfirmed" to be TRUE so that we can do testing tn, and made frontend show how many points are deducted. 
note that it still gives u a congratulations message for losing points lmfao
📷 Screenshots
old stuff still works: 
=> Quick hotfix for working negative scans

src/pages/public/Gamification/Redemption/index.js
Adds an email text field ( accidentally removed in PR#394 ), exactly the same as before
📷 Screenshots
=> Add email text field

src/pages/public/Companion/index.js
🎟️ Ticket(s): Super tiny fix in the schedule
👷 Changes: 
The description for one of the schedules.
📷 Screenshots
=> makes slight change to schedule

src/pages/public/Gamification/Redemption/index.js
=> fix text styling

src/constants/_constants/registration.js, src/pages/admin/DynamicForm/FormRegister.js, src/pages/admin/Event/EventStats/RegistrationField.js, src/pages/public/Companion/Leaderboard.js, src/pages/public/Companion/index.js, src/pages/public/Login.js
=> change stripe flow to handle charlimit

package-lock.json, src/components/alerts/MemberAlert.js, src/components/buttons/RadioGroupButtons.js, src/constants/_constants/config.js, src/pages/admin/DynamicForm/FormRegister.js, src/pages/member/Home/index.js, src/pages/public/Event/EventRegister/EventRegisterForm.js, src/pages/public/Login.js, src/pages/public/LoginRedirect.js, src/pages/public/RegistrationForms/MembershipForm/MembershipForm.js, src/pages/public/RegistrationForms/MembershipForm/index.js, src/pages/public/RegistrationForms/OAuthUserMembershipForm/OAuthUserMembershipForm.js, src/pages/public/RegistrationForms/OAuthUserMembershipForm/index.js, src/pages/public/RegistrationForms/index.js, src/router.js
🎟️ Ticket(s): Closes OAuth login flow 
👷 Changes: Allows users to sign in through an oauth partner (currently Google and Facebook) 
💭 Notes: Oauth user membership can be purchased through the new OAuth User Member form 
- changes go in tandem with server-side PR: https://github.com/ubc-biztech/serverless-biztechapp/pull/257
📷 Screenshots
=> Oauth login

src/constants/_constants/config.js
=> Added localhost to development env

src/pages/public/RegistrationForms/FormSuccess.js, src/pages/public/RegistrationForms/MembershipForm/index.js, src/pages/public/RegistrationForms/OAuthUserMembershipForm/index.js, src/pages/public/RegistrationForms/UserMembershipForm/index.js, src/pages/public/RegistrationForms/index.js
🎟️ Ticket(s): Closes # https://www.notion.so/ubcbiztech/b24732925a6745caa305a2c746fa5ba7?v=d557178d0a134acf85a3890882538364&p=d617ba6f86c746a4aa75ad16e4c34b15&pm=s 
Changed instances of 2022/23 to 2023/24 
there is an asset called biztech_logo_2022.svg that we did not rename, and the logo is pretty universal. It was created in 2022 hence the name.
📷 Screenshots
=> Updating years

src/constants/_constants/companion.js, src/pages/public/Companion/components/CompanionLayout.js, src/pages/public/Companion/components/Schedule.js, src/pages/public/Companion/events/DataAndBeyond2023.js, src/pages/public/Companion/events/index.js, src/pages/public/Companion/index.js
🎟️ Ticket(s): Closes #125
👷 Changes: 
Refactored companion app into a layout and child components, also added a companion object that conditionally renders app based on active event
📷 Screenshots
=> [125] Refactor companion app

src/components/inputs/CustomSelect.js, src/components/inputs/CustomTextField.js, src/pages/public/RegistrationForms/MembershipForm/MembershipForm.js, src/pages/public/RegistrationForms/UserMembershipForm/UserMembershipForm.js, src/pages/public/RegistrationForms/UserMembershipForm/index.js
Fixed MUI errors for forms, registration form no longer throws validation error
📷 Screenshots
=> Bugfix registration form

src/components/inputs/CustomTextField.js, src/pages/public/RegistrationForms/MembershipForm/MembershipForm.js, src/pages/public/RegistrationForms/UserMembershipForm/UserMembershipForm.js, src/pages/public/RegistrationForms/UserMembershipForm/index.js
Reverts ubc-biztech/bt-web#434
=> Revert "Bugfix registration form"

src/router.js
🎟️ Ticket(s): Closes #121
Removed conditional header and footer, this seems to be a leftover companion app change, since the base route redirects to /home and any companion paths only render route, this check is not needed.
📷 Screenshots
https://github.com/ubc-biztech/bt-web/assets/83519492/7f5d89b5-5d15-4998-b038-6f266e6606d5
=> [121] Edit form cutoff

src/pages/admin/DynamicForm/FormCreate.js, src/pages/public/Companion/components/CompanionLayout.js, src/pages/public/Companion/components/FeedbackForm.js, src/pages/public/Companion/index.js
🎟️ Ticket(s): Closes #https://www.notion.so/ubcbiztech/b24732925a6745caa305a2c746fa5ba7?v=d557178d0a134acf85a3890882538364&p=456ac24b122a4e55973235714514b2bd&pm=s
1. Adds a isCompleted flag onto events backend table, and introduces a button to the Event Edit Form to mark an event as completed/uncompleted
2. Shows a feedback form based on the event's feedback form link when the event's isCompleted is true.
📷 Screenshots
Mark as Complete/Uncomplete:
With event.isCompleted == false:
With event.isCompleted == true
mobile:
=> Add feedback form to companion app and isCompleted flag to events

src/pages/admin/Mentors/Mentors.js, src/pages/public/Companion/components/CompanionLayout.js, src/pages/public/Companion/components/mentor/MentorCard.js, src/pages/public/Companion/components/mentor/Mentors.js, src/pages/public/Companion/components/mentor/SearchBar.js, src/pages/public/Companion/events/DataAndBeyond2023.js, src/pages/public/Companion/events/index.js, src/pages/public/Companion/index.js, src/router.js
🎟️ Ticket(s): 
Necessary for making companion apps on hellohacks and MIS night
Moves mentors off of its own router page onto the companion app as a component.
Restyles some mentor components to fit its new living area in the world of companionland
📷 [Screenshots](url)
https://github.com/ubc-biztech/bt-web/assets/48665319/e0cf9b57-5b06-492c-9ad0-1dcbf014671e
=> Modularize mentors and add to companion

src/pages/public/RegistrationForms/UserMembershipForm/index.js
🎟️ Ticket(s): Closes #153 
👷 Changes: Removed validation for education on validation error
Cause for bug: When shcool is selected as "NA", we use the validation error, which requires an education field, education field is left blank when school is selected as "NA", thus the validation error
FIX: add a default selection in useState so that field can never be null, thus education validation is not needed
📷 Screenshots
=> [153] None of the above error

src/pages/admin/DynamicForm/FormRegister.js
=> Bugfix nonmembers redirect

src/pages/public/Companion/components/CompanionLayout.js, src/pages/public/Companion/components/mentor/MentorCard.js, src/pages/public/Companion/components/mentor/Mentors.js, src/pages/public/Companion/components/mentor/SearchBar.js
👷 Changes: Fixed mentor tags to no longer split by spaces, and added autcomplete dropdown for easier tag lookup
📷 Screenshots
https://github.com/ubc-biztech/bt-web/assets/83519492/11895ad3-2c53-4b28-98e9-f99ed2e1a625
=> Fix Mentor Tags + Autocomplete

src/components/alerts/MemberAlert.js, src/pages/public/RegistrationForms/MembershipForm/index.js
=> fixed redirect

src/pages/public/Companion/components/mentor/Mentors.js
=> duplicate skill fix

src/pages/public/Companion/components/mentor/Mentors.js
fixes a Set.contains to Set.has
📷 Screenshots
=> fixed .contains bug

src/pages/public/RegistrationForms/MembershipForm/index.js, src/pages/public/RegistrationForms/OAuthUserMembershipForm/index.js, src/pages/public/RegistrationForms/UserMembershipForm/index.js
🎟️ Ticket(s): Closes #n.a
Updated the message on membership
📷 Screenshots
=> added non guarantee event entry to membership signup

src/pages/admin/DynamicForm/EventRegisterSuccess.js
Changed the msg on registration of event to a hardcoded hello hacks msg.
https://github.com/ubc-biztech/bt-web/compare/dev...reset-success-msg?expand=1 <- Linked. 
📷 Screenshots
=> changed success msg for hello hacks waitlist

src/pages/admin/DynamicForm/EventRegisterSuccess.js
Changes the registration success message to be a message that informs them that they will hear back soon
📷 Screenshots
=> change event register message to be hardcoded waitlist message

src/pages/admin/DynamicForm/FormRegisterPartner.js
👷 Changes: Fixed skills in options not being append to list of skills & validate if only options is filled
📷 Screenshots
=> Fixed skills in options not being append to list of skills & validate if only options is filled

src/constants/_constants/eventStatsStatusFields.js, src/constants/_constants/registration.js, src/pages/admin/DynamicForm/FormCreate.js, src/pages/admin/DynamicForm/FormRegister.js, src/pages/admin/Event/EventStats/EventStatsTable.js, src/pages/admin/Event/EventStats/TableColumns.js, src/pages/admin/Event/EventStats/UserStatusDropdownField.js, src/pages/admin/Event/EventStats/utils.js, src/pages/public/Event/EventRegister/index.js
👷 Changes: New stats table for application based events, new flag in event tuple isApplicationBased, "reviewing" emails sent when a participant registers and emails are not sent upon acceptance and rejection. Previous stats table still exists. 
📷 Screenshots
=> new stat table

src/pages/admin/DynamicForm/EventRegisterSuccess.js
🎟️ Ticket(s): INTERIM SOLUTION FOR # https://www.notion.so/ubcbiztech/b24732925a6745caa305a2c746fa5ba7?v=d557178d0a134acf85a3890882538364&p=b43039995bec41b3b3e7f4eeae26acd2&pm=s
This change is tied with the backend [change](https://github.com/ubc-biztech/serverless-biztechapp/pull/303) that removes the .ics from partner's email confirmations. This change updates the message to reflect the removal of the .ics.
📷 Screenshots
Partner message:
Attendee message:
=> Changed the reg msg for partners to remove the calendar invite message, plus formatting.

src/pages/admin/DynamicForm/FormCreate.js
🎟️ Ticket(s): Workshop hotfix
Changed the autogenerated questions. This is because when workshop questions are created and then changed, there are variables which are never deleted properly (DANGLING POINTER). 
I will be working on this ticket next week.
📷 Screenshots
=> changing autogenerated questions, to hotfix issue related to workshop questions

src/constants/_constants/eventRegisterForm.js, src/pages/admin/DynamicForm/FormCreatePreview.js, src/pages/public/RegistrationForms/MembershipForm/MembershipForm.js, src/pages/public/RegistrationForms/OAuthUserMembershipForm/OAuthUserMembershipForm.js, src/pages/public/RegistrationForms/UserMembershipForm/UserMembershipForm.js
=> Changed pronouns selection from dropdown to checkboxes for multi-selection

src/pages/public/RegistrationForms/MembershipForm/MembershipForm.js, src/pages/public/RegistrationForms/OAuthUserMembershipForm/OAuthUserMembershipForm.js, src/pages/public/RegistrationForms/UserMembershipForm/UserMembershipForm.js
=> fixed styling issues

src/pages/admin/DynamicForm/EventRegisterSuccess.js
🎟️ Ticket(s): Closes # https://www.notion.so/ubcbiztech/b24732925a6745caa305a2c746fa5ba7?v=d557178d0a134acf85a3890882538364&p=f2f9d527942547818b4b35459b33903a&pm=s
removed partner registration confrimation emails
linked with the backend change https://github.com/ubc-biztech/serverless-biztechapp/pull/312
this is merging into @AllanT102 's branch.
📷 Screenshots
partner registration has new msg and does not send email:
regular student registration remains the same:
=> Remove partner email on registration

.github/workflows/firebase-hosting-merge.yml, .github/workflows/firebase-hosting-pull-request.yml
=> changed ot sue old firebase version

.github/workflows/firebase-hosting-merge.yml, .github/workflows/firebase-hosting-pull-request.yml
=> changed tools

.github/workflows/firebase-hosting-merge.yml, .github/workflows/firebase-hosting-pull-request.yml
=> Fix firebase 3

.github/workflows/firebase-hosting-merge.yml, .github/workflows/firebase-hosting-pull-request.yml
Reverts ubc-biztech/bt-web#498
=> Revert "Fix firebase 3"

.github/workflows/firebase-hosting-merge.yml, .github/workflows/firebase-hosting-pull-request.yml
=> removed firebase cli

.github/workflows/firebase-hosting-merge.yml, .github/workflows/firebase-hosting-pull-request.yml
=> added versions to action hosting

src/pages/admin/DynamicForm/FormCreate.js
=> fixed bug where validation was still occuring

src/pages/admin/DynamicForm/FormCreate.js
=> removed log

public/index.html
👷 Changes: Changed main dashboard message
💭 Notes: Nope
📷 Screenshots
=> fixed dashboard message

.vscode/settings.json, src/pages/admin/Companion/index.js, src/pages/public/Gamification/Redemption/index.js
Make QR code scans trackable
A new field in QR codes that corresponds to a type (workshop, partner, booth) that is selectable on QR code creation
📷 Screenshots
=> Track qr scans ticket

src/pages/public/Companion/events/Blueprint2024.js, src/pages/public/Companion/events/index.js
=> fixed lint

src/constants/_constants/emails.js, src/pages/public/Companion/components/CompanionLayout.js, src/pages/public/Companion/index.js, src/pages/public/RegistrationForms/MembershipForm/index.js
=> Companion emails

src/pages/admin/Companion/index.js
Added a textfield to filter QRs
📷 Screenshots
=> textfield to filter qrs

package-lock.json, src/pages/public/Companion/components/mentor/Mentors.js, src/pages/public/Companion/components/mentor/SearchBar.js
👷 Changes: Grabbing the profile photo id from dynamic questions and changed filtering to by company
📷 Screenshots
=> fixed filtering for mentors;

src/pages/public/Companion/components/mentor/MentorCard.js
👷 Changes: render pronouns if present
📷 Screenshots
=> render pronouns if present

src/pages/public/Companion/components/mentor/MentorCard.js, src/pages/public/Companion/components/mentor/Mentors.js
x
👷 Changes: if user clicks on profile image or name it directs to linkedin. Also, title no longer says Name at Company because the chip below already says the company name
📷 Screenshots
=> Added linkedin direct if click on mentor card and title fix

src/pages/public/Companion/components/mentor/Mentors.js, src/pages/public/Companion/events/Blueprint2024.js
=> added descriptivve text

src/pages/public/Gamification/Redemption/index.js
=> hotfix for bp

src/pages/public/Gamification/Redemption/index.js
=> replace vote showcase

src/constants/_constants/emails.js
=> added more emails

src/constants/_constants/emails.js
=> moved to prod

src/constants/_constants/emails.js
=> removed dhruv

src/pages/public/Companion/events/Blueprint2024.js
=> removed reels

src/pages/public/Gamification/Redemption/index.js
When ppl see the redemption page without logging in, the sign in w/ email logic is different since it doesn't have the lowercase validation
📷 Screenshots
=> copy pasted the email logic over from companion/index.js

src/pages/public/Companion/events/TechStyle2024.js
=> added context

src/pages/public/Companion/events/TechStyle2024.js
=> lowered point thresholds

src/pages/public/Companion/index.js, src/pages/public/Gamification/Redemption/index.js
=> fixed emails fr

src/pages/admin/Event/EventStats/EventStatsTable.js, src/pages/admin/Event/EventStats/TableColumns.js
🎟️ Ticket(s): https://www.notion.so/ubcbiztech/b24732925a6745caa305a2c746fa5ba7?v=d557178d0a134acf85a3890882538364&p=d098e2558a5c4099a9be8f031b8b2c7e&pm=s
👷 Changes: custom sorting function for updated at column
📷 Screenshots
=> Fixed sorting in stats table

src/pages/admin/DynamicForm/EventRegisterSuccess.js, src/pages/admin/DynamicForm/FormRegister.js, src/router.js
=> updated success message to reflect accordingly

src/pages/public/Companion/components/CompanionLayout.js, src/pages/public/Companion/components/LogoutButton.js, src/pages/public/Companion/events/Produhacks2024.js, src/pages/public/Companion/index.js
https://www.notion.so/b24732925a6745caa305a2c746fa5ba7?v=d557178d0a134acf85a3890882538364&p=b2706f11b9454395a2d0d99c9affac8d&pm=s&pvs=31
Button that clears localstorage login token and refreshes
removed the confirmation modal as we have a logout button to easily solve the issue of logging into the wrong email now.
i also changed the colour of the mailto link
@isa-leroux448 styling suggestions pls - idk where to place it UI wise.
📷 Screenshots
(prefer animated [gif)](url)
=> added logout button

src/pages/admin/DynamicForm/FormRegister.js
=> fixed incomplete event page

package-lock.json, package.json, src/pages/admin/Event/EventStats/EventStatsTable.js
=> Export hotfix

src/pages/admin/Event/EventStats/EventStatsTable.js, src/pages/admin/Event/EventStats/MassUpdateModal.js, src/pages/admin/Event/EventStats/MassUpdateUserStatus.js, src/pages/public/Companion/components/CompanionLayout.js, src/pages/public/Companion/events/HelloHacks2024.js, src/pages/public/Companion/events/index.js
=> hello-hacks 2024 companion update

src/pages/public/Companion/components/dataverse/Leaderboard.js, src/pages/public/Companion/components/dataverse/Progress.js
- redesigned leaderboard ui
- added css animation for progress bar
📷 Screenshots
=> leaderboard UI update

src/pages/public/Companion/components/dataverse/Leaderboard.js
Changes to be committed:
modified:   src/pages/public/Companion/components/dataverse/Leaderboard.js
- Adjusted leaderboard ui by removing border and background and adding dataverse logo to the top
📷 Screenshots
=> Added dataverse logo to leaderboard UI

package-lock.json, package.json, src/pages/public/Companion/components/dataverse/Progress.js, src/pages/public/Companion/components/dataverse/Quiz.js
- added final question autograding
- added confetti and congratulations page after successful final question submission
- added canvas-confetti package as a dependency
- surprisingly not too laggy
📷 Screenshots
=> Added Congratulations page and autograding to final quesiton

src/pages/public/Companion/components/dataverse/Dashboard.js, src/pages/public/Companion/components/dataverse/Leaderboard.js, src/pages/public/Companion/components/dataverse/Progress.js, src/pages/public/Companion/components/dataverse/Quiz.js, src/pages/public/Companion/components/dataverse/QuizData.js, src/pages/public/Companion/components/dataverse/QuizRoom.js
title + minor changes to removing old ui components and cleaning up case sensitivity for final question
📷 Screenshots
=> Added quiz room dataset downloads and revised quiz questions

src/pages/public/Companion/components/dataverse/QuizData.js
- stupid ahh bug
📷 Screenshots
=> Bug Fix for Quiz 3 having no correct answer

src/pages/admin/DynamicForm/FormRegister.js, src/pages/member/Event/QuickRegisterForm.js
🎟️ Ticket(s): Closes 16/10
👷 Changes: 
- Previously, when user typed an invalid email and tried submitting it, the backend would throw an Object error. Now, there's an alert for the user to fix their email field.
- When an email is finished inputted, check to a regex whether the email is valid. If not valid, create an alert to enter a valid email.
💭 Notes: 
- Maybe it would be better to use a popup component instead? Still waiting on feedback and not super familiar with the bt-web alert system.
📷 Screenshots
(Function is triggered when user clicks away from email input field)
-✅ Looks good on large screens
-✅Looks good on mobile
=> Workshop - Validation Email Fixed

src/pages/public/Companion/components/dataverse/Dashboard.js, src/pages/public/Companion/components/dataverse/Leaderboard.js, src/pages/public/Companion/components/dataverse/Progress.js, src/pages/public/Companion/components/dataverse/Quiz.js, src/pages/public/Companion/components/dataverse/QuizData.js, src/pages/public/Companion/components/dataverse/QuizRoom.js
updated quiz room ui
added final question disable guard
implemented short answer cooldown (just frontend side for now)
replaced questions base don demo feedback
implemented wordle-esque coloring scheme for final question
i am too tired to think rn
📷 Screenshots
=> Quiz Room UI redesign + updated quiz questions + final question adjustments

src/pages/public/Companion/components/dataverse/Progress.js, src/pages/public/Companion/components/dataverse/Quiz.js, src/pages/public/Companion/components/dataverse/QuizData.js, src/pages/public/Companion/components/dataverse/QuizRoom.js
quiz room UI changes, changed hardcoded questions
=> dataverse UI changes

src/pages/public/Companion/components/dataverse/Dashboard.js, src/pages/public/Companion/components/dataverse/Quiz.js, src/pages/public/Companion/components/dataverse/QuizRoom.js
small pr, fixing hardcoded values.
=> fixed hardcoded values due to questions chage

src/pages/public/Companion/components/dataverse/Quiz.js, src/pages/public/Companion/components/dataverse/QuizRoom.js
- added crash course download to each quizroom
- added dataset download to each quizroom
📷 Screenshots
=> Added crash course links and replaced old dataset downloads with new ones

src/pages/public/Companion/components/dataverse/Progress.js
=> Modified final answer

src/pages/public/Companion/components/dataverse/Leaderboard.js, src/pages/public/Companion/components/dataverse/Progress.js, src/pages/public/Companion/components/dataverse/Quiz.js
Now sorts the leaderboard by the time of completion of the final question
=> sorting leaderboard by completion time

src/pages/public/Companion/components/dataverse/Progress.js, src/pages/public/Companion/components/dataverse/Quiz.js, src/pages/public/Companion/components/dataverse/QuizRoom.js
=> Fixed final quiz question and scrambled words for runthrough

src/pages/public/Companion/components/dataverse/Dashboard.js, src/pages/public/Companion/components/dataverse/Progress.js, src/pages/public/Companion/components/dataverse/Quiz.js, src/pages/public/Companion/components/dataverse/QuizData.js, src/pages/public/Companion/components/dataverse/QuizRoom.js
- obfuscated answers to questions using base64 encoding/decoding
- added new dataset questions
- adjusted final questions and hints
- adjusted timer to be min of 50 minutes and time to 3:10pm
📷 Screenshots
=> Implemented Base64 obfuscation, new dataset questions, and finalized final question + hints

src/pages/public/Companion/components/dataverse/Dashboard.js
- one line change: set data challenge deadling to 3:15
📷 Screenshots
=> Set data challenge end hard deadline to 3:15pm

src/pages/public/Companion/components/dataverse/Dashboard.js
=> updated tiem to 3:55

src/pages/public/Companion/components/dataverse/Dashboard.js
=> changed time to 3:40

src/pages/public/Companion/components/dataverse/Dashboard.js
=> bruh i changed time to 3:45
