package-lock.json, package.json, src/App.js, src/components/Event.js, src/components/EventSelector.js, src/components/Router.js
- this PR is mainly to support CTRL+R, so that once an event has been selected a page refresh does not require the user to choose which event they are editing again.
- turns the dropdown list into a link. Clicking an option will redirect to that event's 'page'
- decide which event to show based on the url query param `event`, ie `localhost:3000/?event=cfn2`
- if no event is yet selected, `events/get` will be called twice (once on page load, and once when an event is selected), which is not ideal but at the moment its still fast 
- `Home.js` became `EventSelector.js` and a lot of the logic was moved to `Router.js`
- `Router.js` checks for a query param `event` and chooses whether to render the eventselector or the event page
=> Support refresh page

.gitignore, package-lock.json, src/components/Nav.js, src/components/Router.js
MaterialUI has a lot of stuff that comes with it. We should  import each component individually or else booting up dev server/building takes forever
=> Reduce time to build dev environment by reducing import weight

package.json, src/components/Forms/EditEventForm/EditEventForm.js, src/components/Forms/NewEventForm/NewEventForm.js
- When submitting forms the admin will know whether it was successful or not.
- Will alert admins that duplicate event slug exists and not allow submission
- Successful form submission refreshes app state
- Added `GENERATE_SOURCEMAP=false` to avoid our source code being accessible on prod
Closes #40
=> Alert form submission status and redirect

src/components/EventUserTable.js
When execs navigate to an event, they can change the registration status of each person to registered, waitlisted, checked in, or cancelled (while it was just registered/checked in before). 
The row on the table will change colors appropriately:
Registered = white
Checked In = green
Waitlisted = yellow
Cancelled = red
further changes need to be made such that an email will be sent for all registration status changes, except for being checked in (backend stuff)
**NEW**
**OLD**
=> Registration Status God Power

src/components/Forms/RegisterEvent.js
refactored frontend from genders to pronouns with the options:
- He/Him/His
- She/Her/Hers
- Others (typable field)
NOTE: THE FIELD IS STILL 'gender' IN OUR BACKEND and everywhere else in the frontend - ONLY the frontend of the form has changed
=> refactored genders to pronouns (optional field)

src/pages/member/UserEvents.js
A possible fix for issue #147.
Apparently when I clicked specifically on the 'Registered' filter in the /events page, all the other filter buttons would expand by 2px, causing the inconsistent indentation. Setting a fixed width of 135px for the sidePanelLayout class seems to resolve this problem.
=> fixed left filter bar on UserEvents page

src/constants/_constants/registration.js, src/pages/admin/Event/EventStats/EventStatsTable.js, src/pages/admin/Event/EventStats/index.js
#🎟️ Ticket(s): Closes #203
📷 Screenshots
-Changed Registration status labels (previously was "registered", "checkedIn", etc.)
-made this white & bolded instead of black
-added | in between "Edit Event" and "Public Event Page" links
=> Fixed heardFrom stats table + styling updates on EventStatsTable page

src/pages/public/Event/EventRegister/EventRegisterForm.js
=> Marketing request: add 'Instagram' and 'Linkedin' as options for 'where did you hear about this event' q

src/components/inputs/CustomSelect.js, src/pages/public/Event/EventRegister/EventRegisterForm.js, src/pages/public/Event/EventRegister/index.js
We removed the biztechMemberStatus field for the registration form, but didn't remove the validation check for it. Since it was required, the form always throws a validation check error upon submitting (but we couldn't tell from the UI because the field was removed).
To fix this, I've commented out anything to do with biztechMemberStatus for now.
Also fixed the CustomSelect component to only display scrollbars if the text for the options overflows on mobile devices
These changes have already been deployed to PROD, just wanted to update remote master to be consistent
📷 Screenshots
Example of scrollbar for text overflow for select options
=> MIS Night Form - fix submit button bug and scrollbars on mobile

src/pages/public/MembershipForm/MembershipForm.js, src/pages/public/MembershipForm/index.js
👷 Changes: When a user presses 'submit', the submit button is greyed out & disabled so the user can no longer click it, until the backend call resolves & it brings them to the 'signup success' page. (Before, it would just show nothing so the user didn't know if it was submitting. This lead them to just spam the button, which would then result in error messages of 'A user with this email already exists' even though they were signing up for the first time.)
💭 Notes: 
📷 Screenshots
=> Loading state on submitting membership form

src/components/inputs/CustomTextField.js, src/pages/public/Event/EventRegister/EventRegisterForm.js, src/pages/public/Event/EventRegister/index.js
🎟️ Ticket(s): Closes as a user, I should not be able to change the email on the form when I register for an event
Set the read-only property for emails to true so they cannot be edited. 
📷 Screenshots
=> Added read only property to user emails

src/components/layout/Navigation.js
🎟️ Ticket(s): Logging out does not redirect anywhere and causes crashes
👷 Changes: Added a redirect to the login screen after the user logs out from the dashboard
💭 Notes: If an admin user logs out while the admin-only events page is loading, the app will crash despite the redirect. All other logout scenarios (user/admin) seem to work so far
📷 Screenshots
=> Add push to login screen after logout

src/pages/member/MemberProfile/index.js
🎟️ Ticket(s): As a user, I should not be able to change my email on my profile similar to my student ID
👷 Changes: Set the email field to 'read only' like the student ID field. Added a note to the tooltip so users will know to contact a BizTech exec if they wish to change their email
💭 Notes: N/A
📷 Screenshots
=> Add read only to user profile emails

src/pages/admin/DynamicForm/FormCreate.js
🎟️ Ticket(s): Closes Tooltip feature on imageUrl
Changed textfield div property for imageUrl in formCreate.js
📷 Screenshots
- [ yes ] Looks good on large screens
- [ nope ] Looks good on mobile
=> added Tooltip for imageUrl

src/pages/admin/Home.js, src/pages/public/EventsDashboard.js
🎟️ Ticket(s): Closes ticket where the events page should be showing the upcoming events first
Filtered the events by the most recent start date on the Home and Events dashboard
📷 Screenshots
The video below shows the Events dashboard.
The Home landing page has the same behaviour. 
=> Filtered events by most recent start date

src/pages/admin/DynamicForm/FormCreate.js
🎟️ Ticket(s): Closes #As an admin, I should be able to set a date and time for when the registration period of an event is over
👷 Changes: Registration form to add deadline to sign up
📷 Screenshots
Also did validation to make sure it's not before start date
- [ y] Looks good on large screens
- [ x] Looks good on mobile - but tbh nothing really looks great on mobile...sowry.. it can be a backlog!
=> finished ticket to add registration deadline on admin view

src/pages/public/Event/EventRegister/index.js
🎟️ Ticket(s): Closes As a user, I should not be able to register for an event that is past the registration period
The registration page now informs the user that the event registration has passed and the registration form no longer appears.
If no event deadline is included the event is considered not past the deadline. 
📷 Screenshots
=> Past events registration

src/pages/admin/DynamicForm/FormRegister.js
🎟️ Ticket(s): Closes #As an user, I should be able to see a date and time for when the registration period of an event is over
Adds registration deadline to the user's pov of the event registration form
📷 Screenshots
Deadline Passed:
Live event:
=> Adds registration deadline

src/pages/member/MemberProfile/index.js, src/pages/public/EventsDashboard.js
🎟️ Ticket(s): Closes # N/A
added a "No matching events found" message when no events match the filtered query on member events page.
Also changed all header stylings on member pages to be BIZTECH_GREEN. (if u don't like the look lmk and i'll undo).
if you have styling recommendations on the text, please share.
📷 Screenshots
=> Add no events message and styling

src/components/Event/EventCard.js, src/pages/admin/Home.js
🎟️ Ticket(s): Closes #As a user, when an event has passed, I should see past events shaded out or clearly different then current/ongoing events
👷 Changes: EventCard.js & Home.js - set a property of opacity 50%
Works on both admin, user, and past events tab
📷 Screenshots
- [ yes ] Looks good on large screens
- [ yes ] Looks good on mobile
=> added the greyed out functionality to passed events

src/pages/admin/Event/EventStats/EventStatsTable.js, src/pages/admin/Event/EventStats/utils.js
🎟️ Ticket(s): N/A
EFFECT: when an exec clicks on data within the registration table, the page will crash.
- The Registration Table render override using divs (#329) crashes the page because PopoverCell (#267) requires direct access to a text value. PopoverCell is used to truncate values and display a pop-up modal.
- I've reverted the divs to be [React Fragments](https://reactjs.org/docs/fragments.html) so that PopoverCell can have direct access to the text.value.
- Page no longer crashes on data click and PopoverCell's truncate/pop-up works as expected; see screenshot.
📷 Screenshots
=> Make cell data compatible with PopoverCell

src/constants/_constants/eventRegisterForm.js, src/constants/index.js, src/pages/admin/DynamicForm/FormRegister.js
Sets up a produhacks form which shows varying questions depending on what the user wants to apply for
- moved constants into constants folder for reduced clutter
- Hard codes the domains, "SWE", "PM", "UX", into FormRegister.js to be used as a `questionDomain` state property. Custom questions in the events database are tagged with `questionDomain: "SWE" | "PM" | "UX"`. 
- a new column in Events DB has been added called `hasDomainSpecificQuestions` which determines whether or not a event will use domain specific questions
- the current implementation doesn't add any column onto the admin side registrations table that shows what the user has applied …
=> implemented hardcoded produhacks form with split domain based questions

src/pages/admin/DynamicForm/FormCreate.js
🎟️ Ticket(s): Closes # https://www.notion.so/ubcbiztech/b24732925a6745caa305a2c746fa5ba7?v=d557178d0a134acf85a3890882538364&p=7f8a91ce5f984f719cf57a97dc922d98&pm=s
We added validation on editing a event's startYear, such that you cannot change the startYear to be differnt than the event's year. 
This solves our ticket because the bug in question only happens when an event's startYear has been edited to be different than its original year on creation. (We use the startYear to redirect the url after submitted an event edit)
By blocking admins from changing the startYear to be different from the original year on creation, this bug will never happen.
Wait! Before you merge, …
=> Validate start year on editing events

src/pages/admin/DynamicForm/FormCreate.js, src/pages/admin/DynamicForm/FormRegister.js, src/pages/admin/DynamicForm/components/CustomQuestion.js, src/pages/admin/DynamicForm/components/QuestionPreview.js
🎟️ Ticket(s): Closes # https://www.notion.so/ubcbiztech/b24732925a6745caa305a2c746fa5ba7?v=d557178d0a134acf85a3890882538364&p=7ba1e1b3691f49fcb097cab02fda54d9&pm=s
*Introduced new type of question: (Workshop Selection)
*In workshop selection type of question, admin has capability of placing a maximum capacity for each option.
*Added a default workshop selection question to show admins how this feature works.
*Enabled preview for workshop type of question.
*Collected number of signups from each workshop from backend
*If workshop is full, disabled selection capability with new 'disabled' style.
*Must be tested with backend together which sends the info over.
[GitHub - …
=> Workshop max attendees

src/pages/admin/DynamicForm/FormCreate.js, src/pages/public/RegistrationForms/MembershipForm/index.js, src/pages/public/RegistrationForms/UserMembershipForm/index.js
🎟️ Ticket(s): Closes # 148
👷 Changes: Fixed error in yup when syntax as a result of new yup version
📷 Screenshots
=> Bugfix yup when

src/pages/admin/DynamicForm/FormRegister.js, src/pages/admin/DynamicForm/FormRegisterPartner.js, src/pages/admin/DynamicForm/components/CustomQuestion.js, src/pages/admin/DynamicForm/components/OtherCheckbox.js, src/pages/admin/DynamicForm/components/QuestionPreview.js
🎟️ Ticket(s): Closes #146
👷 Changes: Added other checkbox component, as well as submission check.
💭 Notes: There is a lot of code duplication in the form components, make a ticket to refactor components for less duplication
https://github.com/ubc-biztech/bt-web/assets/83519492/41996e1d-f1f2-4cbb-9da1-c189b8d7107a
https://github.com/ubc-biztech/bt-web/assets/83519492/78b67628-a86c-460d-b73b-ec5d276f3fd2
=> [146] Other Checkbox

src/pages/public/Companion/events/index.js, src/pages/public/Companion/index.js
https://www.notion.so/ubcbiztech/b24732925a6745caa305a2c746fa5ba7?v=d557178d0a134acf85a3890882538364&p=d03551bec133407d93ca81d2c45f7b1c&pm=s
set authentication to false on the call to events/id/year on the companion app. 
This fixes a bug where the companion app was inaccessible if you were logged out on the regular events app
Also adds the locaiton of the event to be asian centre
📷 Screenshots
=> Deauthenticated the companion call to events + updates event location on companion

src/pages/admin/DynamicForm/FormRegister.js, src/pages/admin/DynamicForm/FormRegisterPartner.js
So that Blueprint partners can upload their headshot using our web app.
The File Upload type question now allows for jpg, png, jpeg.
IDEALLY we also address the ticket where files get uploaded to a event specific folder.
Feel free to add onto this branch for that feature.
📷 Screenshots
=> changed the file upload types to include images in registration forms

src/pages/admin/DynamicForm/FormRegister.js
🎟️ Ticket(s): Closes #Make File uploads separate by event
- Most of the changes were in https://script.google.com/home accessible from dev account.
- I created a new script which takes in an additional feature folderID
- If a folder already exists with the same name, the upload goes into that folder.
- If not, then a new folder is created with the folderID name passed through.
The script is called _Updated BT-Web Uploads_
📷 Screenshots
=> Uploads go into seperate folder in dev drive

src/pages/public/Login.js
Added a button to resend verification email on the signing page. When an unverified email tries to log in, they will be able to resend it to their email.
local frontend env was fixed, works fine
📷 Screenshots
=> Add Resend Verification On Login

src/pages/public/RegistrationForms/MembershipForm/MembershipForm.js
bug on #dev-help ???? MAYBE?
make student id non read only on the membership sign up form for people who have accounts but aren't yet members.
i don't know if this is exactly what is causing the bug in #dev-help on slack, but hopefully it does? idk the bug remains unreproducable
📷 Screenshots
didn't test ngl
=> made student id non read only

src/pages/admin/Event/EventStats/EventStatsTable.js, src/pages/admin/Event/EventStats/utils.js
for funsies (also bc it caused major panic when we say 270 regs at blueprint when there was 220 limit)
the events registsration table now shows stats at the bottom specific to attendee or partner
📷 Screenshots
https://github.com/ubc-biztech/bt-web/assets/48665319/a12c375a-280c-4474-962a-7afbaec7df74
^^ audio on please
=> made event stats table show reg stats dependent on whether attendee or partner regs are viewed

src/pages/admin/DynamicForm/FormRegister.js
Prompt user payment on application based events AFTER they are accepted - changes to FormRegister.js to change Proceed to Payment to "Submit" on application based events that require payment. Redirects user straight to success page after registration. Adds users to registration data as incomplete, for payment link to be sent on acceptance. 
My prettier extension may have fumbled a few indents and or new line changes, which is why it says there are so many edits.
📷 Screenshots
=> Prompt user payment on application based events after

src/pages/admin/DynamicForm/FormRegister.js, src/pages/public/Companion/events/Produhacks2024.js
👷 Changes: 
Create new checkout session object every when complete payment is clicked to ensure that user never returns to an expired link. 
Companion does the same
📷 Screenshots
=> create new stripe checkout on complete payment

src/pages/public/Companion/events/Produhacks2024.js
BUG fix
Checkout link wasn't showing since registration.checkoutLink is no longer generated upon applying.
We don't need to check for registration.checkoutLink anymore because of @AllanT102's feature of auto generating link
📷 Screenshots
=> enabled checkout link when link doesn't exist yet

src/pages/public/RegistrationForms/MembershipForm/index.js
Memberships are not being associated properly when a returning BizTech user signs up for a new membership. Their email is automatically converted to lowercase in the membership registration form, but their email key in the users DB might not be all lowercase, so we aren't able to associate the membership to the user. This results in our payments webhook failing to set the user to having `isMember=true`, as seen in the Slack thread.
Email is grabbed from the source of truth on the correct capitalization, `user.email`. We are already passing this in via the `user` prop, and `user.email` is being used to pre-fill the form.
Need to test in `dev` first before we merge to `master`
Related slack thread: https://ubcbiztech202425.slack.com/archives/C071AMV247P/p1725431742940669
=> Fix unnecessary email lowercase

src/pages/public/Companion/events/index.js
👷 Changes: just updated the 'activeUntil' field to be a couple days after hello hacks
💭 Notes: tested by creating hello-hacks 2024 event on bt-web
=> updated event date to be active until oct 8 2024

src/pages/admin/Event/EventStats/TableColumns.js, src/pages/admin/Event/EventStats/utils.js
🎟️ Ticket(s): Closes [this ticket](https://github.com/orgs/ubc-biztech/projects/4?pane=issue&itemId=84600888)
- Added createdAt column in table 
- Tested on local with backend changes made in this PR: https://github.com/ubc-biztech/serverless-biztechapp/pull/398
- For testing I just register users and check that the createdAt time doesn't update when the registrationStatus is updated
- I have no idea how to check if this works for partner registration
After creation:
After update:
=> Add createdAt column in registration table

src/pages/public/Companion/components/dataverse/Dashboard.js, src/pages/public/Companion/components/dataverse/Quiz.js, src/pages/public/Companion/components/dataverse/QuizRoom.js
give the user a hint to the final word
=> Added clue words given at the completion of each quiz

src/pages/public/Companion/components/dataverse/Leaderboard.js
Instead of displaying the points of each team which was double counting. It is now showing the number of unique questions
It is a bit of a hacky fix, however due to the time crunch for dataverse, this is a working and the best solution. If time permits, will come back and fix the double counting issues as a whole.
=> fixed display of double counting points
